using GridForge.Spatial;
using SwiftCollections;
using System;

namespace Trailblazer.Pathing;

/// <summary>
/// Represents the result of a flow field survey operation, including the mapping of world voxel indices 
/// to their associated flow fields and related survey metadata.
/// </summary>
/// <remarks>
/// Use this class to access the flow fields generated by a survey operation, along with information
/// about which charts were utilized and the request key associated with the result. The class provides an empty result
/// instance for cases where no survey data is available.
/// </remarks>
public class FlowFieldSurveyResult : SurveyResult
{
    /// <summary>
    /// Gets the collection of flow fields associated with each world voxel index.
    /// </summary>
    /// <remarks>
    /// The returned dictionary maps each unique world voxel index to its corresponding flow field.
    /// The property may be null if no flow fields have been initialized or assigned.
    /// </remarks>
    public SwiftDictionary<WorldVoxelIndex, FlowField>? Fields { get; private set; }

    internal FlowFieldSamplingGrid[] SamplingGrids { get; private set; } = Array.Empty<FlowFieldSamplingGrid>();

    /// <inheritdoc/>
    public override bool HasPath => IsValid && Fields != null && Fields.Count > 0;

    /// <summary>
    /// Represents an empty result for a flow field survey operation.
    /// </summary>
    /// <remarks>
    /// Use this field to represent a default or uninitialized survey result when no data is available.
    /// </remarks>
    public static readonly FlowFieldSurveyResult Empty = new();

    private FlowFieldSurveyResult() { }

    /// <summary>
    /// Creates a new instance of the FlowFieldSurveyResult class using the specified flow fields, utilized charts, and request key.
    /// </summary>
    /// <param name="context">The world context that owns the survey result.</param>
    /// <param name="fields">A dictionary mapping world voxel indices to their corresponding flow fields. Cannot be null.</param>
    /// <param name="chartsUtilized">An array of chart identifiers that were utilized during the survey. If null, an empty array is used.</param>
    /// <param name="key">The exact cache identity of the request associated with this survey result.</param>
    /// <returns>A FlowFieldSurveyResult instance initialized with the provided flow fields, charts, and request key.</returns>
    public static FlowFieldSurveyResult Create(
        TrailblazerWorldContext context,
        SwiftDictionary<WorldVoxelIndex, FlowField> fields,
        string[] chartsUtilized,
        PathRequestCacheKey key)
    {
        PathRequestContextResolver.ThrowIfUnusable(context);
        return Create(
            context,
            fields,
            chartsUtilized,
            key,
            Array.Empty<FlowFieldSamplingGrid>());
    }

    internal static FlowFieldSurveyResult Create(
        TrailblazerWorldContext context,
        SwiftDictionary<WorldVoxelIndex, FlowField> fields,
        string[] chartsUtilized,
        PathRequestCacheKey key,
        FlowFieldSamplingGrid[] samplingGrids)
    {
        return new FlowFieldSurveyResult()
        {
            IsValid = true,
            Context = context,
            ChartsUtilized = chartsUtilized ?? Array.Empty<string>(),
            Fields = fields,
            SamplingGrids = samplingGrids ?? Array.Empty<FlowFieldSamplingGrid>(),
            LastUsedFrame = -1,
            RequestCacheKey = key
        };
    }

    /// <inheritdoc/>
    public override void Reset()
    {
        base.Reset();
        Fields = null;
        SamplingGrids = Array.Empty<FlowFieldSamplingGrid>();
    }
}
