//=======================================================================
// AStarSurveyResult.cs
//=======================================================================
// MIT License, Copyright (c) 2024-present David Oravsky (mrdav30)
// See LICENSE file in the project root for full license information.
//=======================================================================

using System;

namespace Trailblazer.Pathing;

/// <summary>
/// Represents the result of an A* pathfinding survey, including the computed waypoints and related metadata.
/// </summary>
/// <remarks>
/// Use this class to access the waypoints generated by an A* pathfinding operation, along with
/// information about the charts utilized and the validity of the result.
/// The static Empty instance represents a result with no waypoints.
/// </remarks>
public class AStarSurveyResult : SurveyResult
{
    /// <summary>
    /// Gets the sequence of waypoints that define the calculated path.
    /// </summary>
    /// <remarks>
    /// The array is empty if no path has been found or calculated.
    /// The waypoints are ordered from the start to the end of the path.
    /// </remarks>
    public AStarWaypoint[] Waypoints { get; private set; } = Array.Empty<AStarWaypoint>();

    /// <inheritdoc/>
    public override bool HasPath => IsValid && Waypoints != null && Waypoints.Length > 0;

    /// <summary>
    /// Represents an empty result for an A* survey operation.
    /// </summary>
    public static readonly AStarSurveyResult Empty = new();

    private AStarSurveyResult() { }

    /// <summary>
    /// Creates a new instance of the AStarSurveyResult class with the specified waypoints, charts utilized, and key.
    /// </summary>
    /// <param name="context">The world context that owns the survey result.</param>
    /// <param name="waypoints">An array of AStarWaypoint objects representing the waypoints to include in the survey result. Can be null.</param>
    /// <param name="chartsUtilized">An array of chart names that were utilized in the survey. If null, an empty array is used.</param>
    /// <param name="key">The unique key associated with the survey request.</param>
    /// <returns>A new AStarSurveyResult instance initialized with the provided waypoints, charts utilized, and key.</returns>
    public static AStarSurveyResult Create(
        TrailblazerWorldContext context,
        AStarWaypoint[] waypoints,
        string[] chartsUtilized,
        PathRequestCacheKey key)
    {
        PathRequestContextResolver.ThrowIfUnusable(context);
        return new AStarSurveyResult()
        {
            IsValid = true,
            Context = context,
            ChartsUtilized = chartsUtilized ?? Array.Empty<string>(),
            Waypoints = waypoints,
            LastUsedFrame = -1,
            RequestCacheKey = key
        };
    }

    /// <inheritdoc/>
    public override void Reset()
    {
        base.Reset();
        Waypoints = Array.Empty<AStarWaypoint>();
    }
}
