<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LangVersion>11.0</LangVersion>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<Configurations>Debug;Release;ReleaseLean</Configurations>
		<OutputType>Exe</OutputType>
		<DisableMemoryPack Condition="'$(DisableMemoryPack)' == ''">false</DisableMemoryPack>
		<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'ReleaseLean'">
		<DisableMemoryPack>true</DisableMemoryPack>
		<DefineConstants>$(DefineConstants);TRAILBLAZER_DISABLE_MEMORYPACK</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Trailblazer\Trailblazer.csproj" />
		<PackageReference Include="FluentAssertions" Version="8.10.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
		<PackageReference Include="xunit.v3.runner.console" Version="3.2.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition="'$(DisableMemoryPack)' != 'true'">
		<PackageReference Include="FixedMathSharp.FluentAssertions" Version="7.1.0" Condition="'$(UseLocalLsfStack)' != 'true'" />
	</ItemGroup>
	<ItemGroup Condition="'$(DisableMemoryPack)' == 'true'">
		<PackageReference Include="FixedMathSharp.FluentAssertions.Lean" Version="7.1.0" Condition="'$(UseLocalLsfStack)' != 'true'" />
	</ItemGroup>
	<ItemGroup Condition="'$(UseLocalLsfStack)' == 'true'">
		<ProjectReference Include="..\..\..\FixedMathSharp\src\FixedMathSharp.FluentAssertions\FixedMathSharp.FluentAssertions.csproj"
			AdditionalProperties="Configuration=$(Configuration);SemVer=7.1.0;AssemblySemVer=7.1.0.0" />
		<ProjectReference Include="..\..\..\SwiftCollections\src\SwiftCollections\SwiftCollections.csproj"
			AdditionalProperties="Configuration=$(Configuration);SemVer=7.0.0;AssemblySemVer=7.0.0.0" />
		<ProjectReference Include="..\..\..\GridForge\src\GridForge\GridForge.csproj"
			AdditionalProperties="Configuration=$(Configuration);SemVer=9.1.0;AssemblySemVer=9.1.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Remove=".gitignore" />
	</ItemGroup>
</Project>
